name: GitHub Actions Demo
on: pull_request
jobs:
  linux_x64-gcc10:
    if: ${{ false }}  # disable for now
    runs-on: ubuntu-latest
    container: 
      image: docker.io/synacker2/daggy_gcc10
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache conan packages
        uses: actions/cache@v3
        with:
          path: ~/.conan/data
          key: conan-data

      - name: Make build dir
        run: mkdir build

      - name: Conan install
        working-directory: build
        run: conan install $GITHUB_WORKSPACE --build=missing

      - name: Conan build
        working-directory: build
        run: conan build $GITHUB_WORKSPACE

      - name: Tests
        working-directory: build
        run: ctest -C Release --output-on-failure --output-junit tests/local_tests.xml

      - name: JUnit Report Action
        uses: mikepenz/action-junit-report@v3.2.0
        with:
          report_paths: build/tests/local_tests.xml

      - name: Packaging
        working-directory: build
        run: cpack

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: daggy_linux_x64
          path: |
            build/*.deb
            build/*.rpm
            build/*.zip
  windows-msvs2019:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Cache conan packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.conan/data
            c:\.conan\
          key: conan-data

      - name: Cache QtIFW
        uses: actions/cache@v3
        with:
          path: C:\QtIFW
          key: qt-ifw

      - name: Cache vc_redist
        uses: actions/cache@v3
        with:
          path: downloads
          key: vc_redist

      - name: Cache python pip
        uses: actions/cache@v3
        with:
          path: "%LOCALAPPDATA%/pip/Cache"
          key: pip_cache
      
      - run: pip install conan

      - name: Download vc_redist
        run: |
              if ( -not(Test-Path downloads/vc_redist-x64.exe) ) {
                  $ProgressPreference = 'SilentlyContinue'
                  Invoke-WebRequest -UseBasicParsing -OutFile downloads/vc_redist-x64.exe 'https://aka.ms/vs/16/release/vc_redist.x64.exe'
              }

      - name: Make build dir
        run: mkdir build

      - name: Move vc_redist
        run: mv downloads/vc_redist-x64.exe build/