name: GitHub Actions Demo
on: pull_request
jobs:
  linux_x64-gcc10:
    runs-on: ubuntu-latest
    container: 
      image: docker.io/synacker2/daggy_gcc10
    steps:
      - uses: actions/checkout@v3
      - name: Print current working dir
        run: |
          echo $PWD
          ls -la $PWD
          echo $GITHUB_WORKSPACE
          ls -la $GITHUB_WORKSPACE

     