name: GitHub Actions Demo
on: pull_request
jobs:
  linux_x64-gcc10:
    runs-on: ubuntu-latest
    container: 
      image: docker.io/synacker2/daggy_gcc10
    steps:
      - uses: actions/checkout@v3

      - name: Cache conan packages
        uses: actions/cache@v3
        with:
          path: $HOME/.conan/data
          key: conan-data

      - name: Make build dir
        run: mkdir build

      - name: Conan install
        working-directory: build
        run: conan install $GITHUB_WORKSPACE --build=missing

      - name: Conan build
        working-directory: build
        run: conan build $GITHUB_WORKSPACE
