name: GitHub Actions Demo
on: pull_request
jobs:
  linux_x64-gcc10:
    runs-on: ubuntu-latest
    container: 
      image: docker.io/synacker2/daggy_gcc10
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache conan packages
        uses: actions/cache@v3
        with:
          path: ~/.conan/data
          key: conan-data

      - name: Make build dir
        run: mkdir build

      - name: Conan install
        working-directory: build
        run: conan install $GITHUB_WORKSPACE --build=missing

      - name: Conan build
        working-directory: build
        run: conan build $GITHUB_WORKSPACE

      - name: Tests
        working-directory: build
        run: ctest -C Release --output-on-failure --output-junit tests/local_tests.xml

      - name: Publish Test Report
        working-directory: build
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: tests/local_tests.xml

      - name: Packaging
        working-directory: build
        run: cpack

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        working-directory: build
        with:
          path: |
            *.deb
            *.rpm
            *.zip


