name: GitHub Actions Demo
on: push
jobs:
  linux_x64-gcc10:
    runs-on: ubuntu-latest
    env:
      GITHUB_WORKSPACE: /home/daggy 
      CONAN_USER_HOME: ${{GITHUB_WORKSPACE}}
    container: 
      image: docker.io/synacker2/daggy_gcc10
      options: --user daggy
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        path: daggy
        
      - name: Cache conan packages
        uses: actions/cache@v3
        with:
          path: |
            .conan/data

      - name: Conan install
        working-directory: build
        run: conan install ../daggy --build=missing
